### ISSUE TITLE
honor system crypto policy

### ISSUE THREAD

**Issue by nwalfield** [rpm-software-management/rpm-sequoia#14]
As per [@pmatilai's mail](https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/message/WYQV24N6MF3ZMF5CAAMZTANB64R54ISS/) to fedora-devel:

>>> - Some old, insecure (MD5/SHA1 based) signatures are rejected (this is
>>> in line with the stronger crypto settings proposed elsewhere for F38)
>> 
>> Such a hardcoded restriction, without a way for the local administrator to
>> allow the legacy signatures, is not acceptable.
>
>Mind you, I don't exactly agree with this style of explicit disabling
>either (see
>https://lists.rpm.org/pipermail/rpm-maint/2021-October/018344.html and
>onwards). But. I doubt many people realize just how thin the ice is
>(and has always been) with the existing parser. I consider this step a
>matter of survival, and ultimately some legacy content becoming harder
>to use is an acceptable tradeoff for *that*.
>
>I don't know how deep this all is wired inside Sequoia, but I totally
>agree (as you see in the thread linked above) that this should be
>based on the system crypto policy. As explained in the change, nettle
>(which doesn't support the system crypto policies AIUI) should be seen
>as a temporary stepstone in Fedora, with a plan to switch to openssl
>(which does) in the nearish future.
>
>So technically this is a matter of "Sequoia should honor system crypto
>policy", rpm is just a dumb API user here that sometimes get told
>"nope" by the underlying libraries, whether due to crypto policy, FIPS
>or whatever.

See also: https://gitlab.com/sequoia-pgp/sequoia/-/issues/857

**Comment by nwalfield** [comment]
Relevant related work: https://fedoraproject.org/wiki/Changes/StrongCryptoSettings2 https://gitlab.com/redhat-crypto/fedora-crypto-policies

**Comment by pmatilai** [comment]
Thanks for this! From the initial discussions around this topic on rpm-maint I feared this all may be more hardwired in Sequoia than it is.

**Comment by nwalfield** [comment]
@pmatilai, [you wrote](https://gitlab.com/sequoia-pgp/sequoia/-/issues/857#note_1139080450):

> For rpm(-sequoia), returning failure from rpmInitCrypto() would be the best way of handling a malformed config file (and other similar).

Unfortunate, [`rpmInitCrypto`](https://github.com/rpm-software-management/rpm/blob/master/include/rpm/rpmcrypto.h#L41) can only indicate failure by returning -1.  So far, I've avoided using `rpm`'s logging machinery in `rpm-sequoia`.  What should I do if the file is not found or malformed?  Should I just emit a message or `stderr` and return failure?

**Comment by nwalfield** [comment]
I've pushed a draft PR.  The following issues are open:

  - Location of the policy file (@t184256)
  - A test policy file (@t184256)
  - How to display parsing errors (@pmatilai)
  - How to disable reading the policy file, e.g., when run `make check` on `rpm` (@t184256, @pmatilai)

Thanks everyone.

**Comment by nwalfield** [comment]
FYI:

```
$ cat /usr/share/crypto-policies/policies/sequoia.pol 
[hash_algorithms]
sha256 = "never"
sha512 = "never"
$ sq inspect /tmp/alice.asc 
/tmp/alice.asc: OpenPGP Certificate.

    Fingerprint: 3D7EB0048D966F6CD5B358282D6EC06DCF4DD0AC
Public-key algo: EdDSA Edwards-curve Digital Signature Algorithm
Public-key size: 256 bits
  Creation time: 2022-10-25 12:51:04 UTC
      Key flags: certification
...
$ LD_LIBRARY_PATH=/tmp/rpm-sequoia/release ./rpmkeys --import /tmp/alice.asc
warning: Certificate 2D6EC06DCF4DD0AC:
  Policy rejects subkey 161BAC041623145A: Policy rejected ECDH key derivation hash function
$ sudo mv /usr/share/crypto-policies/policies/sequoia.pol{,-}
$ LD_LIBRARY_PATH=/tmp/rpm-sequoia/release ./rpmkeys --import /tmp/alice.asc
$ echo $?
0
```

**Comment by t184256** [comment]
> Location of the policy file

`/etc/crypto-policies/back-ends/sequoia.config`

> A test policy file

Depends on what you want there! So far your

```
[hash_algorithms]
sha256.second_preimage_resistance = "never"
sha512.second_preimage_resistance = "never"
```

from the comment above is the best approximation I have.
Ideally I'd list what's allowed; format and possible values are on you.

What's that format, some INI variation? That dot in key makes it invalid TOML.

> How to disable reading the policy file

Other libraries go for a envvar of which config to read,
with `/etc/crypto-policies/back-ends/<backend>.config`
as a default, configurable on compile time.

> e.g., when run make check on rpm (@t184256, @pmatilai)

I'm not sure `make check` is a good use case.
Ideally there should be an API to override defaults from vendor's policy
and tests can exercise it to enable functionality they want to test.

**Comment by nwalfield** [comment]
> > Location of the policy file
> 
> `/etc/crypto-policies/back-ends/sequoia.config`

Thanks, I'll update the PR.

https://docs.rs/sequoia-policy-config/0.2.0/sequoia_policy_config/

> Depends on what you want there! So far your
> 
> ```
> [hash_algorithms]
> sha256.second_preimage_resistance = "never"
> sha512.second_preimage_resistance = "never"
> ```
> 
> from the comment above is the best approximation I have. Ideally I'd list what's allowed; format and possible values are on you.
> 
> What's that format, some INI variation?

I think there is a misunderstanding.  Perhaps you didn't see [the documentation](https://docs.rs/sequoia-policy-config/0.2.0/sequoia_policy_config/).  It describes the configuration file format, and provides lots of examples.  If that is not enough or unclear, I'd appreciate it if you could tell me what is confusing or missing.

> What's that format, some INI variation? That dot in key makes it invalid TOML.

What parser are you using?  According to [the spec](https://toml.io/en/v1.0.0), these are called "dotted keys" and are recognized by Rust's TOML parser.

> Other libraries go for a envvar of which config to read,
> with /etc/crypto-policies/back-ends/<backend>.config
> as a default, configurable on compile time.

That's reasonable.  Unless someone has an opinion, I'll use `RPM_SEQUOIA_CONFIG`, and hard code the default, for now.

> > e.g., when run make check on rpm (@t184256, @pmatilai)
> 
> I'm not sure `make check` is a good use case.
> Ideally there should be an API to override defaults from vendor's policy and tests can exercise it to enable functionality they want to test.

Isn't an environment variable an API?  Can you please be more concrete about what you imagine.  Thanks!

**Comment by pmatilai** [comment]
An environment variable to override default is nice.

We could always copy possible system policy configs to the testing root, it's not a big deal to add. This hasn't been an issue with openssl (ie there are no errors) though, so I guess it just falls back to library defaults.

As for reporting errors, emitting on stderr is a perfectly reasonable thing to do here.

**Comment by nwalfield** [comment]
@pmatilai : Thanks for following up.

> This hasn't been an issue with openssl (ie there are no errors) though, so I guess it just falls back to library defaults.

When the config is not present, falling back to the system default seems perfectly reasonable.  I'm more worried about a system policy prohibiting something that a test relies on.  That would be a pain to debug.

> As for reporting errors, emitting on stderr is a perfectly reasonable thing to do here.

Thanks for the confirmation.

**Comment by pmatilai** [comment]
>  When the config is not present, falling back to the system default seems perfectly reasonable. I'm more worried about a system policy prohibiting something that a test relies on. That would be a pain to debug.

Right, this hasn't come up so far, but that's probably more to do with luck than anything else.
OTOH, the main use-case for the test-suite is the CI, where it executes in a known environment. While we accept patches to make it work in other distros and versions, I don't think many bother (because we're not getting such patches or reports), and fakechroot availability and stability issues don't help that. Which is just to say, it's not something to lose sleep over.

**Comment by t184256** [comment]
> I think there is a misunderstanding. Perhaps you didn't see [the documentation](https://docs.rs/sequoia-policy-config/0.2.0/sequoia_policy_config/).

Indeed, sorry. Cool format, it's a pity I won't use dates.

> What parser are you using?

Sigh, the parser I've reached out for has been 0.4.0. Sorry for the noise.

> Isn't an environment variable an API? Can you please be more concrete about what you imagine. Thanks!

I meant, unless the policy implements library defaults that can be overridden with some subsequent Rust call that relaxes them, application developers will soon find a case when they have to interoperate with something legacy and demand an override for their special case. Seems like [there are such overrides](https://docs.rs/sequoia-openpgp/1.10.0/sequoia_openpgp/policy/struct.StandardPolicy.html) available already. So tests relying on specific algorithms should be able to use them.

**Comment by t184256** [comment]
Do I understand correctly, that there's no way to prohibit a future `sha4` from being enabled by default through that config?

**Comment by nwalfield** [comment]
> Do I understand correctly, that there's no way to prohibit some future `sha4` from being enabled by default through that config if I can't predict its name?

That's correct.  What would you like to do?  Prohibit all algorithms that aren't explicitly allowed?  FWIW, we are relatively careful about what algorithms we enable by default in the standard policy.

**Comment by t184256** [comment]
Trying a distribution builder hat on, I'd prefer to allowlist algorithms instead of denylisting them, yes. While I put reasonable trust in upstream judgement about newly added and enabled by default algorithms being secure, that shiny new SHA-4 upstream's enabling could be, say, not yet approved by certification authorities downstream cares about. Possibly similar concerns apply to application writers as well.

GnuTLS [comes to mind](https://fedoraproject.org/wiki/Changes/GnutlsAllowlisting), where we've ended up introducing a configuration flag that optionally turns its denylisting configuration upside down into an allowlisting mode instead.
That was no small feat =/

But we've veered off-topic. Do you want a separate RFE filed about it?

**Comment by nwalfield** [comment]
@t184256 : Please open an issue here https://gitlab.com/sequoia-pgp/sequoia/-/issues asking for an enhancement to `StandardPolicy`.

You say we've veered off-topic, but I'm unclear what the conclusion is: is the config file format good enough or not?

**Comment by t184256** [comment]
Good enough to start, not all back-ends go the preferred allowlisting way. https://gitlab.com/sequoia-pgp/sequoia/-/issues/941 filed.

**Comment by t184256** [comment]
I've got a draft at

https://gitlab.com/redhat-crypto/fedora-crypto-policies/-/merge_requests/122

Please refer to `tests/outputs/{LEGACY,DEFAULT,FUTURE}-sequoia.txt` as examples of desired configuration as I understood it.

**Comment by nwalfield** [comment]
> Good enough to start, not all back-ends go the preferred allowlisting way. https://gitlab.com/sequoia-pgp/sequoia/-/issues/941 filed.

You can now do the following:

```
[symmetric_algorithms]
aes128 = "2040-01-01"
aes256 = "2050-01-01"
default_disposition = "never"
```

This causes all algorithms to be rejected by default.  See: https://gitlab.com/sequoia-pgp/sequoia-policy-config/-/commit/ff89dbd14731300ec4ce61c8b087a16ae359b141

**Comment by nwalfield** [comment]
Thanks everyone.  This is part of v1.1.1 of rpm-sequoia, which I just released.

In the end, the environment variable is called `SEQUOIA_CRYPTO_POLICY`.
