### ISSUE TITLE
Missing key on v3 signatures returns FAIL instead of NOKEY in 1.1.2

### ISSUE THREAD

**Issue by pmatilai** [rpm-software-management/rpm-sequoia#28]
As per https://bugzilla.redhat.com/show_bug.cgi?id=2141686#c35:

NOKEY return doesn't seem to work with V3 signatures. With eg https://archives.fedoraproject.org/pub/archive/fedora/linux/releases/30/Everything/x86_64/os/Packages/3/389-admin-console-doc-1.1.12-8.fc30.noarch.rpm I'm getting:

```
[pmatilai🎩︎localhost _build]$ ./rpmkeys -Kv /tmp/389-admin-console-doc-1.1.12-8.fc30.noarch.rpm
/tmp/389-admin-console-doc-1.1.12-8.fc30.noarch.rpm:
    Header V3 RSA/SHA256 Signature, key ID cfc659b9: BAD
    Header SHA256 digest: OK
    Header SHA1 digest: OK
    Payload SHA256 digest: OK
    V3 RSA/SHA256 Signature, key ID cfc659b9: BAD
    MD5 digest: OK
```

...whereas with the internal parser:
```
$ rpmkeys -Kv /tmp/389-admin-console-doc-1.1.12-8.fc30.noarch.rpm
/tmp/389-admin-console-doc-1.1.12-8.fc30.noarch.rpm:
    Header V3 RSA/SHA256 Signature, key ID cfc659b9: NOKEY
    Header SHA256 digest: OK
    Header SHA1 digest: OK
    Payload SHA256 digest: OK
    V3 RSA/SHA256 Signature, key ID cfc659b9: NOKEY
    MD5 digest: OK
```

I'll try to get https://github.com/rpm-software-management/rpm/issues/2276 ASAP, manually testing all the cases gets old and error prone real fast.

**Comment by nwalfield** [comment]
Hmm, I see `NOKEY`:

```
$ RPM_TRACE=0 ~/rpm-4.18/b/rpmkeys -Kv /tmp/389-admin-console-doc-1.1.12-8.fc30.noarch.rpm 
/tmp/389-admin-console-doc-1.1.12-8.fc30.noarch.rpm:
    Header V3 RSA/SHA256 Signature, key ID cfc659b9: NOKEY
    Header SHA256 digest: OK
    Header SHA1 digest: OK
    Payload SHA256 digest: OK
    V3 RSA/SHA256 Signature, key ID cfc659b9: NOKEY
    MD5 digest: OK
[neal@fedora-36 rpm-sequoia]$ git describe
v1.1.2-8-g2a0ad53
[neal@fedora-36 rpm-4.18]$ git describe
rpm-4.18.0-release
```

Can you rerun with `RPM_TRACE=1` and send me the trace, please.

**Comment by pmatilai** [comment]
Oh, just realized I'm talking about 1.1.2 whereas it's 1.2.0 that added the support for v3 keys, no?

**Comment by nwalfield** [comment]
Correct.

**Comment by pmatilai** [comment]
Yup, my bad then, I somehow managed to grab 1.1.2 as the latest from koji for local testing. With 1.2.0 it's as expected. Sorry for the false alarm!

**Comment by nwalfield** [comment]
No worries!  I'd rather help debug a few false positives then not know about some true positives.
