### ISSUE TITLE
Return error messages

### ISSUE THREAD

**Issue by nwalfield** [rpm-software-management/rpm-sequoia#39]
@panu writes:

Based on the number of new crypto related issues folks are running into on Fedora, maybe we should consider some emergency bandaid for better error messages.

Such as simply a new pgpVerifySignature() variant which has an additional char **emsg argument to return a message from the lower level. The main consumer of that is rpmKeyringVerifySig() from which we can use rpmlog() to output any error so it gets handled in dnf callbacks and stuff. Ideally the message would be returned to rpmKeyringVerifySig() instead, but then ideally this whole API would be very different so adding two more bad APIs seems worse than adding just one :D

From: https://github.com/rpm-software-management/rpm/issues/2127#issuecomment-1482646398

**Comment by pmatilai** [comment]
Guess we might as well take the discussion here, the only relevant messages would be coming from Sequoia anyhow. I'm thinking something like this from the caller side (rpmKeyringVerifySig()):

```
        char *emsg = NULL;
        rc = pgpVerifySignature2(pgpkey, sig, ctx, &emsg);

        if (emsg) { 
            int lvl = (rc == RPMRC_FAIL) ? RPMLOG_ERR : RPMLOG_WARNING;
            rpmlog(lvl, "%s", emsg);
            free(emsg);
        }

```

That should allow us to lecture people about their obsolete crypto while still functioning...

**Comment by pmatilai** [comment]
...but feel free to suggest something different, eg if you'd like to pass more info there or something. If we're adding a new API then doing something more isn't any more expensive as long as pgpVerifySignature() can easily be implemented with it for compatibility.

**Comment by nwalfield** [comment]
Exactly that API is what is in my prototype.  Great minds think alike or something ;)

**Comment by nwalfield** [comment]
It's the same pattern that we are using in pgpPubKeyLint, btw

**Comment by pmatilai** [comment]
Heh. And I totally forgot about pgpPubkeyLint.

All we need is a name then, I do dislike adding numbers to function names :confounded:

**Comment by nwalfield** [comment]
@pmatilai: This is probably not the final version.  FWIW, it doesn't break the rpm test suite.  I'd appreciate if you could take a look.

**Comment by nwalfield** [comment]
@pmatilai, here's the new output, what do you think?

```
$ sudo update-crypto-policies --set DEFAULT
$ LD_PRELOAD=$HOME/rpm-sequoia/target/release/librpm_sequoia.so RPM_TRACE=0 ./rpm -i ~/anydesk-6.1.1-1.el7.x86_64.rpm 
error: Verifying a signature using certificate D56311E5FF3B6F39D5A16ABE18DF3741CDFFDE29 (philandro Software GmbH <info@philandro.com>):
  Certificate 18DF3741CDFFDE29 invalid: policy violation
      because: No binding signature at time 2021-04-13T11:08:37Z
error: /home/neal/anydesk-6.1.1-1.el7.x86_64.rpm: Header V3 RSA/SHA1 Signature, key ID cdffde29: BAD
error: /home/neal/anydesk-6.1.1-1.el7.x86_64.rpm cannot be installed
$ sudo update-crypto-policies --set FUTURE
$ LD_PRELOAD=$HOME/rpm-sequoia/target/release/librpm_sequoia.so ./rpm -i ~/anydesk-6.1.1-1.el7.x86_64.rpm 
error: Verifying a signature using certificate D56311E5FF3B6F39D5A16ABE18DF3741CDFFDE29 (philandro Software GmbH <info@philandro.com>):
  1. Signature 155143, created at Tue Apr 13 11:08:37 2021 invalid: it relies on legacy cryptography
      because: Policy rejected non-revocation signature (Binary) requiring collision resistance
      because: SHA1 is not considered secure since 1970-01-01T00:00:00Z
  2. Certificate 18DF3741CDFFDE29 invalid: policy violation
      because: No binding signature at time 2021-04-13T11:08:37Z
error: /home/neal/anydesk-6.1.1-1.el7.x86_64.rpm: Header V3 RSA/SHA1 Signature, key ID cdffde29: BAD
error: /home/neal/anydesk-6.1.1-1.el7.x86_64.rpm cannot be installed
$ LD_PRELOAD=$HOME/rpm-sequoia/target/release/librpm_sequoia.so RPM_TRACE=0 ./rpm -i ~/google-chrome-stable-109.0.5414.119-1.x86_64.rpm 
error: Verifying a signature using certificate 4CCA1EAF950CEE4AB83976DCA040830F7FAC5991 (Google, Inc. Linux Package Signing Key <linux-packages-keymaster@google.com>):
  1. Signature 2179, created at Mon Jan 23 21:23:32 2023 invalid: it relies on legacy cryptography
      because: Policy rejected non-revocation signature (Binary) requiring collision resistance
      because: SHA1 is not considered secure since 1970-01-01T00:00:00Z
  2. Certificate A040830F7FAC5991 invalid: policy violation
      because: No binding signature at time 2023-01-23T21:23:32Z
      because: Policy rejected non-revocation signature (PositiveCertification) requiring second pre-image resistance
      because: SHA1 is not considered secure since 1970-01-01T00:00:00Z
warning: /home/neal/google-chrome-stable-109.0.5414.119-1.x86_64.rpm: Header V4 DSA/SHA1 Signature, key ID 7fac5991: NOTTRUSTED
error: Failed dependencies:
	rpmlib(PayloadIsXz) <= 5.2-1 is needed by google-chrome-stable-109.0.5414.119-1.x86_64
```

**Comment by pmatilai** [comment]
Ooh, crypto errors with actual reasoning :flushed: 
That's really nice!

This caught my eye though:
> because: SHA1 is not considered secure since 1970-01-01T00:00:00Z

Maybe it's a side-effect of how the policy implements it (I wouldn't know), but claiming SHA1 not considered secure decades before it was even invented does seem a bit odd :smile:
