### ISSUE TITLE
New RPM doesn't like Amazon Linux 2023 signing key

### ISSUE THREAD

**Issue by ozbenh** [rpm-software-management/rpm-sequoia#58]
The amazon linux 2023 signing key upsets newer RPMs (such as in Fedora 38). The key can be found here:

https://raw.githubusercontent.com/xsuchy/distribution-gpg-keys/main/keys/amazon-linux/RPM-GPG-KEY-amazon-linux-2023

sq seems to like it enough:

```
sq inspect RPM-GPG-KEY-amazon-linux-2023
RPM-GPG-KEY-amazon-linux-2023: OpenPGP Certificate.

    Fingerprint: B21C50FA44A99720EAA72F7FE951904AD832C631
Public-key algo: RSA (Encrypt or Sign)
Public-key size: 4096 bits
  Creation time: 2022-12-08 16:14:49 UTC

         UserID: Amazon Linux <amazon-linux@amazon.com>
```

But trying to import it results in:

```
$ sudo rpm --import RPM-GPG-KEY-amazon-linux-2023 
warning: Certificate E951904AD832C631:
  Certificate does not have any usable signing keys
```

and `rpm` also refuses to open any Amazon Linux 2023 packages (which effectively breaks using `mkosi` (which I'm trying to add AL2023 support to) from a recent Fedora or even Ubuntu):

```
$ rpm -qpi bash-5.2.15-1.amzn2023.0.2.x86_64.rpm 
error: Verifying a signature using certificate B21C50FA44A99720EAA72F7FE951904AD832C631 (Amazon Linux <amazon-linux@amazon.com>):
  Key E951904AD832C631 invalid: not signing capable
error: bash-5.2.15-1.amzn2023.0.2.x86_64.rpm: Header V4 RSA/SHA512 Signature, key ID d832c631: BAD
error: bash-5.2.15-1.amzn2023.0.2.x86_64.rpm: not an rpm package (or package manifest)
```
This RPM can be obtained here:

https://cdn.amazonlinux.com/al2023/core/guids/9cf1057036ef7d615de550a658447fad88617805da0cfc9b854ba0fb8a668466/x86_64/../../../../blobstore/7788b494301e4b43761962716e25f799cf4411e74e472772714a58e7dc08f1b4/bash-5.2.15-1.amzn2023.0.2.x86_64.rpm

The RPMs are signed using a custom internal solution, so we might have an issue with our signatures format but I am concerned that the key itself already seems to upset rpm.

I'm not a PGP expert, so any advice here would be welcome. Unfortunately I don't see any way for us to replace the key and re-sign all our packages :-(

**Comment by nwalfield** [comment]
Thanks for reporting this issue.

Looking at the certificate with `sq packet dump`, I see:

```
$ sq packet dump RPM-GPG-KEY-amazon-linux-2023 
Public-Key Packet, new CTB, 525 bytes
    Version: 4
    Creation time: 2022-12-08 16:14:49 UTC
    Pk algo: RSA
    Pk size: 4096 bits
    Fingerprint: B21C50FA44A99720EAA72F7FE951904AD832C631
    KeyID: E951904AD832C631
  
User ID Packet, new CTB, 38 bytes
    Value: Amazon Linux <amazon-linux@amazon.com>
  
Signature Packet, new CTB, 635 bytes
    Version: 4
    Type: PositiveCertification
    Pk algo: RSA
    Hash algo: SHA512
    Hashed area:
      Signature creation time: 2022-12-12 18:46:26 UTC (critical)
      Issuer: E951904AD832C631
      Notation: salt@notations.sequoia-pgp.org
        00000000  cf 56 b6 84 f9 7f dd 9a  fa 21 07 e4 da 2e 64 05
        00000010  da ee 04 b7 63 bf c2 8a  46 68 ce 86 c8 bf a6 31
      Issuer Fingerprint: B21C50FA44A99720EAA72F7FE951904AD832C631
    Digest prefix: 2035
    Level: 0 (signature over data)
```

There are a few interesting things going on.  The most important, and the reason why `rpm` and sequoia are rejecting it, is that the self signature does not include a [Key Flags subpacket](https://datatracker.ietf.org/doc/html/rfc4880#section-5.2.3.21), which means the key is unusable.  The Key Flags subpacket is used to indicate the contexts / domains in which key material is allowed to be used (e.g., signing, certification, authentication, encryption at rest, encryption in transit, etc.)   This separation can help reduce cross domain attacks, like the [SHA-1 is a Shambles attack](https://sha-mbles.github.io/) in which a data signature ("signing flag") is repurposed as a certification ("certification flag").

The question is: why doesn't your self signature include the Key Flags subpacket.

The self signature appears to be generated by sequoia based on the presence of the `salt@notations.sequoia-pgp.org` notation.  This suggests a bug in Sequoia.  What's curious though is that the self signature was generated on December 12, 2022, but the primary key was created on December 8, 2022.  Do you know the history of this certificate?

**Comment by wiktor-k** [comment]
> What's curious though is that the self signature was generated on December 12, 2022, but the primary key was created on December 8, 2022. Do you know the history of this certificate?

Maybe it was generated by some other piece of software and then a modification of the key was handled by Sequoia and Sequoia just copied the data from a previous self-sig which was buggy? (Just my speculation)

**Comment by ozbenh** [comment]
Thanks,  I don't know off hand, I'm asking internally.

**Comment by ozbenh** [comment]
Also do you happen to know if this is the only issue or there is also something wrong with the signature in the RPMs ? rpm won't open them even when told not to check and even when the key isn't enrolled. I know this is generated by some custom internal tooling (the key probably as well) as it's all hosted in AWS KMS

**Comment by ozbenh** [comment]
btw. in another issue you extracted the key from the RPM for manual inspection, how do you do that ? I didn't find an option in rpm, rpmsign, or elsewhere...

**Comment by stewartsmith** [comment]
Amusingly enough we just went through a bunch of debugging on this :)

Our GPG key used for signing comes from the key being stored in KMS, and some wrapper code that then uses it to produce a GPG signature of the kind that RPM likes. It also exports the public key from KMS in the GPG format.

This export of the public key followed the letter of the spec for what packets are required for exchanging a key, which, rather interestingly, do *not* include the flags. Prior versions of `rpm` were fine with this, so it wasn't an issue.

So the `rpm-sequoia` behavior is a behavior change for RPM, and is imposing an extra requirement on the keys, although I'm not convinced it's a bug worth fixing rather than just documenting the behavior change since anyone with the private key can easily generate an updated export of the public key that fixes the issue.

The fix for us was adding `.set_key_flags(KeyFlags::empty().set_certification().set_signing()` in the pubilc key export code path.

**Comment by stewartsmith** [comment]
The timing of Dec 8th vs 18th is that the key would have been generated in KMS on the 8th, and the running of the program to produce the gpg public key export would have been run on the 12th (in reality, probably also earlier, but the one out there was the one from the 12th).

**Comment by ozbenh** [comment]
Yup, I've tested an updated key successfully, thanks. Closing

**Comment by nwalfield** [comment]
Great to hear that it's now working.  Out of curiosity, what software are you using?  Is it a homegrown, internal tool, or actually published someplace?  Thanks!

**Comment by nwalfield** [comment]
By the way, [this commit](https://github.com/rpm-software-management/rpm-sequoia/tree/neal/save-signature-to-file) saves the signature to `/tmp/rpm.sig`.

**Comment by nwalfield** [comment]
> This export of the public key followed the letter of the spec for what packets are required for exchanging a key, which, rather interestingly, do not include the flags. Prior versions of rpm were fine with this, so it wasn't an issue.

I agree that the the Key Flags subpacket is not required for a certificate to be well-formed.  But I don't think that well-formed implies that a certificate is usable for signing.

The specification says [the following about the Key Flags subpacket](https://datatracker.ietf.org/doc/html/rfc4880#section-5.2.3.21):

>  This subpacket contains a list of binary flags that hold information
>   about a key.  It is a string of octets, and an implementation MUST
>  NOT assume a fixed size.  This is so it can grow over time.  If a
>   list is shorter than an implementation expects, the unstated flags
>   are considered to be zero.

Sequoia's interpretation is that if the key flags subpacket is not present, the key flags list is empty.  The text doesn't explicitly say that, but it also doesn't say what the value of the key flags should be if it is not present, or that the self signature is malformed if the subpacket is not present.

> So the rpm-sequoia behavior is a behavior change for RPM, and is imposing an extra requirement on the keys,

My perspective is that the internal parser was buggy in this regard, and Sequoia fixes this (among a bunch of other issues).

If you think that Sequoia is behaving incorrectly or poorly, I'd be interested in hearing why.  Thanks!

**Comment by stewartsmith** [comment]
On Sep 29, 2023, at 2:53 AM, Neal H. Walfield ***@***.***> wrote:
> Great to hear that it's now working. Out of curiosity, what software are you using? Is it a homegrown, internal tool, or actually published someplace? Thanks!

It’s home grown (using existing libraries), but our intent is to publish once we’d worked out the kinks, and manage to get some documentation in order.

**Comment by stewartsmith** [comment]
On Sep 29, 2023, at 3:17 AM, Neal H. Walfield ***@***.***> wrote:
> 
> So the rpm-sequoia behavior is a behavior change for RPM, and is imposing an extra requirement on the keys,
> 
> My perspective is that the internal parser was buggy in this regard, and Sequoia fixes this (among a bunch of other issues).
> 
I think this is completely fair, especially as it’s 100% fixable for us. We seem to have deployed the fix and nothing has broken… so now that I’ve said that there’ll be something :)
> If you think that Sequoia is behaving incorrectly or poorly, I'd be interested in hearing why.
> 

Honestly, the excellent documentation really helped us able to work out what was going on and how to fix it.

**Comment by nwalfield** [comment]
Thanks for the feedback!
