### ISSUE TITLE
License mismatch

### ISSUE THREAD

**Issue by subnut** [rpm-software-management/rpm-sequoia#64]
https://github.com/rpm-software-management/rpm-sequoia/blob/739a606da6ea1e836a415a1fd7899f36b7fd5a38/Cargo.toml#L11

https://github.com/rpm-software-management/rpm-sequoia/blob/739a606da6ea1e836a415a1fd7899f36b7fd5a38/LICENSE.txt#L1-L4

**Comment by nwalfield** [comment]
What is the difference?

**Comment by subnut** [comment]
There is no difference/mismatch.

Sorry for the noise.

There are two people running this account, and the other guy posted this without consulting me.

Please do delete this issue if you can.

Thank you and have a good day.

**Comment by pmatilai** [comment]
> There are two people running this account

That a direct violation of GitHub's terms of service: https://docs.github.com/en/site-policy/github-terms/github-terms-of-service#b-account-terms :

> Your login may only be used by one person — i.e., a single login may not be shared by multiple people. A paid Organization may only provide access to as many Personal Accounts as your subscription allows.

Just FWIW.
