### ISSUE TITLE
Look for config in /usr as well

### ISSUE THREAD

**Issue by DaanDeMeyer** [rpm-software-management/rpm-sequoia#65]
The UAPI group is trying to work towards working image-based Linux systems that contain only /usr (see https://github.com/uapi-group/specifications/issues/76). To make this work it'd be great if rpm-sequoia would look for its policy in /usr/share/crypto-policies if the environment variables aren't set and no config file is found in /etc/crypto-policies

**Comment by nwalfield** [comment]
Sorry for not responding.  In #72, I've changed `rpm-sequoia` to first look for the crypto policy in `/etc/crypto-policies/back-ends/rpm-sequoia.config`, and if that does not exist, `/usr/share/crypto-policies/back-ends/rpm-sequoia.config`.

**Comment by DaanDeMeyer** [comment]
@nwalfield I just took a look and on Fedora the rpm-sequoia default config in /usr is shipped in a different location `/usr/share/crypto-policies/back-ends/DEFAULT/rpm-sequoia.config `. Any chance rpm-sequoia could look there?

**Comment by nwalfield** [comment]
@DaanDeMeyer: I don't know anything about this.  It would be good if we did the right thing and not just changed paths randomly.  Could you please find out what the officially sanctioned way to find the correct location is and follow up here?  Thanks!
